version: "3.9"

services:

  homebrew-db:
    container_name: homebrew-db
    image: "postgres:14.1"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
    volumes:
      - /home/maxabillion/Documents/projects/PowerAttackPublishingDB/sql:/sql

  homebrew-write:
    container_name: homebrew-write
    image: homebrew-py:0.0.1
    command: "python -u db.py"
    environment:
      DATA_PATH: $DATA_PATH
      TABLE_NAME: $TABLE_NAME
    volumes:
      - .:/app
    working_dir: /app

  spells:
    container_name: homebrew-spells
    image: homebrew-py:0.0.1
    command: "python -u scripts/spells.py"
    environment:
      SPELLS_DIR: $SPELLS_DIR
      SPELLS_DATA_PATH: $SPELLS_DATA_PATH
    volumes:
      - .:/app
    working_dir: /app

  monsters:
    container_name: homebrew-monsters
    image: homebrew-py:0.0.1
    command: "python -u scripts/monsters.py"
    environment:
      MONSTERS_DIR: $MONSTERS_DIR
      MONSTERS_DATA_PATH: $MONSTERS_DATA_PATH
    volumes:
      - .:/app
    working_dir: /app
